spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kneu
    username: postgres
    password: postgres
    thymeleaf:
    suffix: .html
    mode: HTML5
    prefix: classpath:/templates/
  data:
    pageable:
      defaultPageSize: 3
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
    
 

university:
  maxGroupSize: 30
  vocationDurationBykind:
    GENERAL: 14
    PREFERENTIAL: 24


 
