hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
hibernate.hbm2ddl.auto: update
hibernate.show_sql: true
hibernate.format_sql: true
current_session_context_class: thread
hibernate.enable_lazy_load_no_trans: true
spring.data.pageable.defaulPageSize: 3


spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/kneu
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5
spring.thymeleaf.prefix: classpath:/templates/

group.maxSize: 30
vocation.durationBykind: {GENERAL:'14', PREFERENTIAL:'24'}
page.defaultPageSize: 5

