package ua.com.foxminded.krailo.domain;

import java.time.LocalTime;
import java.time.MonthDay;
import java.util.ArrayList;

public class Main {

    public static void main(String[] args) {
	
	System.out.println("-- Create university office ");
	UniversityOffice universityOffice = new UniversityOffice("KNEU");
	System.out.println(universityOffice);
	System.out.println("-- Create holiday");
	Holiday holidayNewYear = new Holiday("New year", MonthDay.of(12, 1));
	Holiday holidayIndependantDay = new Holiday("Independant Day", MonthDay.of(8, 24));
	System.out.println(holidayNewYear);
	System.out.println(holidayIndependantDay);
	System.out.println("-- Add hoiday to university");
	universityOffice.setHolidays(new ArrayList<>());
	universityOffice.getHolidays().add(holidayNewYear);
	universityOffice.getHolidays().add(holidayIndependantDay);
	System.out.println(universityOffice.getHolidays());
	System.out.println("-- Create faculty");
	Faculty faculty = new Faculty("Faculty of Finance and Economy");
	System.out.println(faculty);
	System.out.println("-- Create speciality");
	Speciality specialityFinance = new Speciality("Finance");
	Speciality specialityBanking = new Speciality("Banking");
	System.out.println(specialityFinance);
	System.out.println(specialityBanking);
	System.out.println("-- Add speciality to faculty");
	faculty.setSpecialities(new ArrayList<>());
	faculty.getSpecialities().add(specialityFinance);
	faculty.getSpecialities().add(specialityBanking);
	System.out.println(faculty.getSpecialities());
	System.out.println("-- Create department");
	Department department = new Department("Department of Financial faculty");
	System.out.println(department);
	System.out.println("-- Add department to faculty");
	faculty.setDepartments(new ArrayList<>());
	faculty.getDepartments().add(department);
	System.out.println(faculty.getDepartments());
	System.out.println("-- Create teachers");
	Teacher teacher1 = new Teacher("Teacher","One");
	Teacher teacher2 = new Teacher("Teacher","Two");
	Teacher teacher3 = new Teacher("Teacher","Three");
	Teacher teacher4 = new Teacher("Teacher","Four");
	Teacher teacher5 = new Teacher("Teacher","Five");
	Teacher teacher6 = new Teacher("Teacher","Six");
	Teacher teacher7 = new Teacher("Teacher","Seven");
	Teacher teacher8 = new Teacher("Teacher","Eight");
	System.out.println("-- Add teacher to department");
	department.setTeachers(new ArrayList<>());
	department.getTeachers().add(teacher1);
	department.getTeachers().add(teacher2);
	department.getTeachers().add(teacher3);
	department.getTeachers().add(teacher4);
	department.getTeachers().add(teacher5);
	department.getTeachers().add(teacher6);
	department.getTeachers().add(teacher7);
	department.getTeachers().add(teacher8);
	System.out.println(department.getTeachers());
	System.out.println("-- Create DeansOffice");
	DeansOffice deansOffice = new DeansOffice("Deans office of Financial faculty");
	System.out.println(deansOffice);
	System.out.println("-- Add deancsOffice to faculty");
	faculty.setDeansOffice(deansOffice);
	System.out.println(faculty.getDeansOffice());
	System.out.println("-- Create Yrear for finance and banking");
	Year year1Finance = new Year("1 year");
	Year year2Finance = new Year("2 year");
	Year year1Banking = new Year("1 year");
	Year year2Banking = new Year("2 year");
	System.out.println(year1Finance);
	System.out.println(year2Finance);
	System.out.println(year1Banking);
	System.out.println(year2Banking);
	System.out.println("-- Add speciality to year");
	year1Finance.setSpeciality(faculty.getSpecialities().get(0));
	year2Finance.setSpeciality(faculty.getSpecialities().get(0));
	year1Banking.setSpeciality(faculty.getSpecialities().get(1));
	year2Banking.setSpeciality(faculty.getSpecialities().get(1));
	System.out.println(year1Finance);
	System.out.println(year2Finance);
	System.out.println(year1Banking);
	System.out.println(year2Banking);
	System.out.println("-- Add year to specialities");
	faculty.getSpecialities().get(0).setYears(new ArrayList<>());
	faculty.getSpecialities().get(0).getYears().add(year1Finance);
	faculty.getSpecialities().get(0).getYears().add(year2Finance);
	faculty.getSpecialities().get(1).setYears(new ArrayList<>());
	faculty.getSpecialities().get(1).getYears().add(year1Banking);
	faculty.getSpecialities().get(1).getYears().add(year2Banking);
	System.out.println(specialityFinance.getYears());
	System.out.println(specialityBanking.getYears());
	System.out.println("-- Create group");
	Group group1FinanceYear1 = new Group("1 group");
	Group group2FinanceYear1 = new Group("2 group");
	Group group1FinanceYear2 = new Group("1 group");
	Group group2FinanceYear2 = new Group("2 group");
	Group group1BankingYear1 = new Group("1 group");
	Group group2BankingYear1 = new Group("2 group");
	Group group1BankingYear2 = new Group("1 group");
	Group group2BankingYear2 = new Group("2 group");
	System.out.println("-- Add speciality and year to group");
	group1FinanceYear1.setSpeciality(specialityFinance);
	group1FinanceYear1.setYear(year1Finance);
	group2FinanceYear1.setSpeciality(specialityFinance);
	group2FinanceYear1.setYear(year1Finance);
	group1FinanceYear2.setSpeciality(specialityFinance);
	group1FinanceYear2.setYear(year2Finance);
	group2FinanceYear2.setSpeciality(specialityFinance);
	group2FinanceYear2.setYear(year2Finance);
	group1BankingYear1.setSpeciality(specialityBanking);
	group1BankingYear1.setYear(year1Banking);
	group2BankingYear1.setSpeciality(specialityBanking);
	group2BankingYear1.setYear(year1Banking);
	group1BankingYear2.setSpeciality(specialityBanking);
	group1BankingYear2.setYear(year2Banking);
	group2BankingYear2.setSpeciality(specialityBanking);
	group2BankingYear2.setYear(year2Banking);
	System.out.println(group1FinanceYear1);
	System.out.println(group2FinanceYear1);
	System.out.println(group1FinanceYear2);
	System.out.println(group2FinanceYear2);
	System.out.println(group1BankingYear1);
	System.out.println(group2BankingYear1);
	System.out.println(group1BankingYear2);
	System.out.println(group2BankingYear2);
	System.out.println("-- Add group to year");
	faculty.getSpecialities().get(0).getYears().get(0).setGroups(new ArrayList<>());
	faculty.getSpecialities().get(0).getYears().get(1).setGroups(new ArrayList<>());
	faculty.getSpecialities().get(1).getYears().get(0).setGroups(new ArrayList<>());
	faculty.getSpecialities().get(1).getYears().get(1).setGroups(new ArrayList<>());	
	faculty.getSpecialities().get(0).getYears().get(0).getGroups().add(group1FinanceYear1);
	faculty.getSpecialities().get(0).getYears().get(0).getGroups().add(group2FinanceYear1);
	faculty.getSpecialities().get(0).getYears().get(1).getGroups().add(group1FinanceYear2);
	faculty.getSpecialities().get(0).getYears().get(1).getGroups().add(group2FinanceYear2);
	faculty.getSpecialities().get(1).getYears().get(0).getGroups().add(group1BankingYear1);
	faculty.getSpecialities().get(1).getYears().get(0).getGroups().add(group2BankingYear1);
	faculty.getSpecialities().get(1).getYears().get(1).getGroups().add(group1BankingYear2);
	faculty.getSpecialities().get(1).getYears().get(1).getGroups().add(group2BankingYear2);
	System.out.println(year1Finance.getGroups());
	System.out.println(year2Finance.getGroups());
	System.out.println(year1Banking.getGroups());
	System.out.println(year2Banking.getGroups());
	System.out.println("-- Create subject");
	Subject subjectFinance1 = new Subject("subject Finance 1");
	Subject subjectFinance2 = new Subject("subject Finance 2");
	Subject subjectFinance3 = new Subject("subject Finance 3");
	Subject subjectFinance4 = new Subject("subject Finance 4");
	Subject subjectBanking1 = new Subject("subject Banking 1");
	Subject subjectBanking2 = new Subject("subject Banking 2");
	Subject subjectBanking3 = new Subject("subject Banking 3");
	Subject subjectBanking4 = new Subject("subject Banking 4");
	System.out.println("-- Add teacher to subject");
	subjectFinance1.setTeachers(new ArrayList<>());
	subjectFinance2.setTeachers(new ArrayList<>());
	subjectFinance3.setTeachers(new ArrayList<>());
	subjectFinance4.setTeachers(new ArrayList<>());
	subjectBanking1.setTeachers(new ArrayList<>());
	subjectBanking2.setTeachers(new ArrayList<>());
	subjectBanking3.setTeachers(new ArrayList<>());
	subjectBanking4.setTeachers(new ArrayList<>());
	subjectFinance1.getTeachers().add(teacher1);
	subjectFinance2.getTeachers().add(teacher2);
	subjectFinance3.getTeachers().add(teacher3);
	subjectFinance4.getTeachers().add(teacher4);
	subjectBanking4.getTeachers().add(teacher5);
	subjectBanking4.getTeachers().add(teacher6);
	subjectBanking4.getTeachers().add(teacher7);
	subjectBanking4.getTeachers().add(teacher8);
	System.out.println("-- Add subject to years");
	year1Finance.setSubjects(new ArrayList<>());
	year2Finance.setSubjects(new ArrayList<>());
	year1Banking.setSubjects(new ArrayList<>());
	year2Banking.setSubjects(new ArrayList<>());
	year1Finance.getSubjects().add(subjectFinance1);
	year1Finance.getSubjects().add(subjectFinance2);
	year2Finance.getSubjects().add(subjectFinance3);
	year2Finance.getSubjects().add(subjectFinance4);
	year1Banking.getSubjects().add(subjectBanking1);
	year1Banking.getSubjects().add(subjectBanking2);
	year2Banking.getSubjects().add(subjectBanking3);
	year2Banking.getSubjects().add(subjectBanking4);
	System.out.println(year1Finance.getSubjects());
	System.out.println(year2Finance.getSubjects());
	System.out.println(year1Banking.getSubjects());
	System.out.println(year2Banking.getSubjects());
	System.out.println("-- Create lessons time");
	LessonTime lessonTime1 = new LessonTime("First lesson", LocalTime.of(8, 30), LocalTime.of(9, 15));
	LessonTime lessonTime2 = new LessonTime("Second lesson", LocalTime.of(9, 30), LocalTime.of(10, 15));
	System.out.println("-- Create Lessons time schedule and add lessons time");
	LessonsTimeSchedule lessonsTimeSchedule = new LessonsTimeSchedule("lessons time schedule");
	lessonsTimeSchedule.setLessonTimes(new ArrayList<>());
	lessonsTimeSchedule.getLessonTimes().add(lessonTime1);
	lessonsTimeSchedule.getLessonTimes().add(lessonTime2);
	System.out.println(lessonsTimeSchedule.getLessonTimes());
	
    }
}
