package ua.com.foxminded.krailo.domain;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.MonthDay;
import java.util.ArrayList;

public class Main {

    public static void main(String[] args) {
	
	System.out.println("-- Create university office ");
	UniversityOffice universityOffice = new UniversityOffice("KNEU");
	System.out.println("-- Create holiday");
	Holiday holidayNewYear = new Holiday("New year", MonthDay.of(12, 1));
	Holiday holidayIndependantDay = new Holiday("Independant Day", MonthDay.of(8, 24));
	System.out.println("-- Add hoiday to university");
	universityOffice.setHolidays(new ArrayList<>());
	universityOffice.getHolidays().add(holidayNewYear);
	universityOffice.getHolidays().add(holidayIndependantDay);
	System.out.println("-- Create faculty");
	Faculty faculty = new Faculty("Faculty of Finance and Economy");
	System.out.println("-- Create speciality");
	Speciality specialityFinance = new Speciality("Finance");
	Speciality specialityBanking = new Speciality("Banking");
	System.out.println("-- Add speciality to faculty");
	faculty.setSpecialities(new ArrayList<>());
	faculty.getSpecialities().add(specialityFinance);
	faculty.getSpecialities().add(specialityBanking);
	System.out.println("-- Create department");
	Department department = new Department("Department of Financial faculty");
	System.out.println("-- Add department to faculty");
	faculty.setDepartments(new ArrayList<>());
	faculty.getDepartments().add(department);
	System.out.println("-- Create teachers");
	Teacher teacher1 = new Teacher("Teacher","One");
	Teacher teacher2 = new Teacher("Teacher","Two");
	Teacher teacher3 = new Teacher("Teacher","Three");
	Teacher teacher4 = new Teacher("Teacher","Four");
	Teacher teacher5 = new Teacher("Teacher","Five");
	Teacher teacher6 = new Teacher("Teacher","Six");
	Teacher teacher7 = new Teacher("Teacher","Seven");
	Teacher teacher8 = new Teacher("Teacher","Eight");
	System.out.println("-- Add teacher to department");
	department.setTeachers(new ArrayList<>());
	department.getTeachers().add(teacher1);
	department.getTeachers().add(teacher2);
	department.getTeachers().add(teacher3);
	department.getTeachers().add(teacher4);
	department.getTeachers().add(teacher5);
	department.getTeachers().add(teacher6);
	department.getTeachers().add(teacher7);
	department.getTeachers().add(teacher8);
	System.out.println("-- Create DeansOffice");
	DeansOffice deansOffice = new DeansOffice("Deans office of Financial faculty");
	System.out.println("-- Add deancsOffice to faculty");
	faculty.setDeansOffice(deansOffice);
	System.out.println("-- Create Yrear for finance and banking");
	Year year1Finance = new Year("1 year");
	Year year2Finance = new Year("2 year");
	Year year1Banking = new Year("1 year");
	Year year2Banking = new Year("2 year");
	System.out.println("-- Add speciality to year");
	year1Finance.setSpeciality(faculty.getSpecialities().get(0));
	year2Finance.setSpeciality(faculty.getSpecialities().get(0));
	year1Banking.setSpeciality(faculty.getSpecialities().get(1));
	year2Banking.setSpeciality(faculty.getSpecialities().get(1));
	System.out.println("-- Add year to specialities");
	faculty.getSpecialities().get(0).setYears(new ArrayList<>());
	faculty.getSpecialities().get(0).getYears().add(year1Finance);
	faculty.getSpecialities().get(0).getYears().add(year2Finance);
	faculty.getSpecialities().get(1).setYears(new ArrayList<>());
	faculty.getSpecialities().get(1).getYears().add(year1Banking);
	faculty.getSpecialities().get(1).getYears().add(year2Banking);
	System.out.println("-- Create group");
	Group group1FinanceYear1 = new Group("1 group");
	Group group2FinanceYear1 = new Group("2 group");
	Group group1FinanceYear2 = new Group("1 group");
	Group group2FinanceYear2 = new Group("2 group");
	Group group1BankingYear1 = new Group("1 group");
	Group group2BankingYear1 = new Group("2 group");
	Group group1BankingYear2 = new Group("1 group");
	Group group2BankingYear2 = new Group("2 group");
	System.out.println("-- Add speciality and year to group");
	group1FinanceYear1.setSpeciality(specialityFinance);
	group1FinanceYear1.setYear(year1Finance);
	group2FinanceYear1.setSpeciality(specialityFinance);
	group2FinanceYear1.setYear(year1Finance);
	group1FinanceYear2.setSpeciality(specialityFinance);
	group1FinanceYear2.setYear(year2Finance);
	group2FinanceYear2.setSpeciality(specialityFinance);
	group2FinanceYear2.setYear(year2Finance);
	group1BankingYear1.setSpeciality(specialityBanking);
	group1BankingYear1.setYear(year1Banking);
	group2BankingYear1.setSpeciality(specialityBanking);
	group2BankingYear1.setYear(year1Banking);
	group1BankingYear2.setSpeciality(specialityBanking);
	group1BankingYear2.setYear(year2Banking);
	group2BankingYear2.setSpeciality(specialityBanking);
	group2BankingYear2.setYear(year2Banking);
	System.out.println("-- Add group to year");
	faculty.getSpecialities().get(0).getYears().get(0).setGroups(new ArrayList<>());
	faculty.getSpecialities().get(0).getYears().get(1).setGroups(new ArrayList<>());
	faculty.getSpecialities().get(1).getYears().get(0).setGroups(new ArrayList<>());
	faculty.getSpecialities().get(1).getYears().get(1).setGroups(new ArrayList<>());	
	faculty.getSpecialities().get(0).getYears().get(0).getGroups().add(group1FinanceYear1);
	faculty.getSpecialities().get(0).getYears().get(0).getGroups().add(group2FinanceYear1);
	faculty.getSpecialities().get(0).getYears().get(1).getGroups().add(group1FinanceYear2);
	faculty.getSpecialities().get(0).getYears().get(1).getGroups().add(group2FinanceYear2);
	faculty.getSpecialities().get(1).getYears().get(0).getGroups().add(group1BankingYear1);
	faculty.getSpecialities().get(1).getYears().get(0).getGroups().add(group2BankingYear1);
	faculty.getSpecialities().get(1).getYears().get(1).getGroups().add(group1BankingYear2);
	faculty.getSpecialities().get(1).getYears().get(1).getGroups().add(group2BankingYear2);
	System.out.println("-- Create subject");
	Subject subject1Finance = new Subject("Economy");
	Subject subject2Finance = new Subject("Meth");
	Subject subject3Finance = new Subject("Data Analysis");
	Subject subject4Finance = new Subject("Accounting");
	Subject subject1Banking = new Subject("Banking Sysytem");
	Subject subject2Banking = new Subject("Riscs");
	Subject subject3Banking = new Subject("Ensuarence");
	Subject subject4Banking = new Subject("Low");
	System.out.println("-- Add teacher to subject");
	subject1Finance.setTeachers(new ArrayList<>());
	subject2Finance.setTeachers(new ArrayList<>());
	subject3Finance.setTeachers(new ArrayList<>());
	subject4Finance.setTeachers(new ArrayList<>());
	subject1Banking.setTeachers(new ArrayList<>());
	subject2Banking.setTeachers(new ArrayList<>());
	subject3Banking.setTeachers(new ArrayList<>());
	subject4Banking.setTeachers(new ArrayList<>());
	subject1Finance.getTeachers().add(teacher1);
	subject2Finance.getTeachers().add(teacher2);
	subject3Finance.getTeachers().add(teacher3);
	subject4Finance.getTeachers().add(teacher4);
	subject1Banking.getTeachers().add(teacher5);
	subject2Banking.getTeachers().add(teacher6);
	subject3Banking.getTeachers().add(teacher7);
	subject4Banking.getTeachers().add(teacher8);
	System.out.println("-- Add subject to years");
	year1Finance.setSubjects(new ArrayList<>());
	year2Finance.setSubjects(new ArrayList<>());
	year1Banking.setSubjects(new ArrayList<>());
	year2Banking.setSubjects(new ArrayList<>());
	year1Finance.getSubjects().add(subject1Finance);
	year1Finance.getSubjects().add(subject2Finance);
	year2Finance.getSubjects().add(subject3Finance);
	year2Finance.getSubjects().add(subject4Finance);
	year1Banking.getSubjects().add(subject1Banking);
	year1Banking.getSubjects().add(subject2Banking);
	year2Banking.getSubjects().add(subject3Banking);
	year2Banking.getSubjects().add(subject4Banking);
	System.out.println("-- Create lessons time");
	LessonTime lessonTime1 = new LessonTime("First lesson", LocalTime.of(8, 30), LocalTime.of(9, 15));
	LessonTime lessonTime2 = new LessonTime("Second lesson", LocalTime.of(9, 30), LocalTime.of(10, 15));
	System.out.println("-- Create Lessons time schedule and add lessons time");
	LessonsTimeSchedule lessonsTimeSchedule = new LessonsTimeSchedule("lessons time schedule");
	lessonsTimeSchedule.setLessonTimes(new ArrayList<>());
	lessonsTimeSchedule.getLessonTimes().add(lessonTime1);
	lessonsTimeSchedule.getLessonTimes().add(lessonTime2);
	System.out.println("-- Create audience");
	Audience audience1 = new Audience("audience 1");
	Audience audience2 = new Audience("audience 2");
	Audience audience3 = new Audience("audience 3");
	Audience audience4 = new Audience("audience 4");
	System.out.println("-- Create building and add audiences");
	Building building = new Building("Main building");
	building.setAudiences(new ArrayList<>());
	building.getAudiences().add(audience1);
	building.getAudiences().add(audience2);
	building.getAudiences().add(audience3);
	building.getAudiences().add(audience4);
	System.out.println("-- Create lessons");
	Lesson lesson1Year1Finance1 = new Lesson(LocalDate.of(2020, 12, 1), subject1Finance, audience1, lessonTime1, teacher1);
	Lesson lesson2Year1Finance1 = new Lesson(LocalDate.of(2020, 12, 1), subject2Finance, audience1, lessonTime2, teacher2);
	Lesson lesson1Year1Banking1 = new Lesson(LocalDate.of(2020, 12, 1), subject1Banking, audience2, lessonTime1, teacher3);
	Lesson lesson2Year1Banking1 = new Lesson(LocalDate.of(2020, 12, 1), subject2Banking, audience2, lessonTime2, teacher4);
	Lesson lesson1Year1Finance2 = new Lesson(LocalDate.of(2020, 12, 2), subject1Finance, audience1, lessonTime1, teacher1);
	Lesson lesson2Year1Finance2 = new Lesson(LocalDate.of(2020, 12, 2), subject2Finance, audience1, lessonTime2, teacher2);
	Lesson lesson1Year1Banking2 = new Lesson(LocalDate.of(2020, 12, 2), subject1Banking, audience2, lessonTime1, teacher3);
	Lesson lesson2Year1Banking2 = new Lesson(LocalDate.of(2020, 12, 2), subject2Banking, audience2, lessonTime2, teacher4);
	Lesson lesson1Year1Finance3 = new Lesson(LocalDate.of(2020, 12, 3), subject1Finance, audience1, lessonTime1, teacher1);
	Lesson lesson2Year1Finance3 = new Lesson(LocalDate.of(2020, 12, 3), subject2Finance, audience1, lessonTime2, teacher2);
	Lesson lesson1Year1Banking3 = new Lesson(LocalDate.of(2020, 12, 3), subject1Banking, audience2, lessonTime1, teacher3);
	Lesson lesson2Year1Banking3 = new Lesson(LocalDate.of(2020, 12, 3), subject2Banking, audience2, lessonTime2, teacher4);	
	System.out.println("-- Add groups to lessons");
	lesson1Year1Finance1.setGroups(new ArrayList<>());
	lesson2Year1Finance1.setGroups(new ArrayList<>());
	lesson1Year1Banking1.setGroups(new ArrayList<>());
	lesson2Year1Banking1.setGroups(new ArrayList<>());	
	lesson1Year1Finance2.setGroups(new ArrayList<>());
	lesson2Year1Finance2.setGroups(new ArrayList<>());
	lesson1Year1Banking2.setGroups(new ArrayList<>());
	lesson2Year1Banking2.setGroups(new ArrayList<>());	
	lesson1Year1Finance3.setGroups(new ArrayList<>());
	lesson2Year1Finance3.setGroups(new ArrayList<>());
	lesson1Year1Banking3.setGroups(new ArrayList<>());
	lesson2Year1Banking3.setGroups(new ArrayList<>());	
	lesson1Year1Finance1.getGroups().add(group1FinanceYear1);
	lesson1Year1Finance1.getGroups().add(group2FinanceYear1);
	lesson2Year1Finance1.getGroups().add(group1FinanceYear1);
	lesson2Year1Finance1.getGroups().add(group2FinanceYear1);	
	lesson1Year1Banking1.getGroups().add(group1BankingYear1);
	lesson1Year1Banking1.getGroups().add(group2BankingYear1);
	lesson2Year1Banking1.getGroups().add(group1BankingYear1);
	lesson2Year1Banking1.getGroups().add(group2BankingYear1);	
	lesson1Year1Finance2.getGroups().add(group1FinanceYear1);
	lesson1Year1Finance2.getGroups().add(group2FinanceYear1);
	lesson2Year1Finance2.getGroups().add(group1FinanceYear1);
	lesson2Year1Finance2.getGroups().add(group2FinanceYear1);	
	lesson1Year1Banking2.getGroups().add(group1BankingYear1);
	lesson1Year1Banking2.getGroups().add(group2BankingYear1);
	lesson2Year1Banking2.getGroups().add(group1BankingYear1);
	lesson2Year1Banking2.getGroups().add(group2BankingYear1);	
	lesson1Year1Finance3.getGroups().add(group1FinanceYear1);
	lesson1Year1Finance3.getGroups().add(group2FinanceYear1);
	lesson2Year1Finance3.getGroups().add(group1FinanceYear1);
	lesson2Year1Finance3.getGroups().add(group2FinanceYear1);	
	lesson1Year1Banking3.getGroups().add(group1BankingYear1);
	lesson1Year1Banking3.getGroups().add(group2BankingYear1);
	lesson2Year1Banking3.getGroups().add(group1BankingYear1);
	lesson2Year1Banking3.getGroups().add(group2BankingYear1);	
	System.out.println("-- Create timetable");
	Timetable timetableFinanceYear1 = new Timetable("Timetable", specialityFinance, year1Finance);
	System.out.println("-- Add lessons to timetable");
	timetableFinanceYear1.setLessons(new ArrayList<>());
	timetableFinanceYear1.getLessons().add(lesson1Year1Finance1);
	timetableFinanceYear1.getLessons().add(lesson2Year1Finance1);
	timetableFinanceYear1.getLessons().add(lesson1Year1Banking1);
	timetableFinanceYear1.getLessons().add(lesson2Year1Banking1);	
	timetableFinanceYear1.getLessons().add(lesson1Year1Finance2);
	timetableFinanceYear1.getLessons().add(lesson2Year1Finance2);
	timetableFinanceYear1.getLessons().add(lesson1Year1Banking2);
	timetableFinanceYear1.getLessons().add(lesson2Year1Banking2);	
	timetableFinanceYear1.getLessons().add(lesson1Year1Finance3);
	timetableFinanceYear1.getLessons().add(lesson2Year1Finance3);
	timetableFinanceYear1.getLessons().add(lesson1Year1Banking3);
	timetableFinanceYear1.getLessons().add(lesson2Year1Banking3);	
	System.out.println("-- Add groups to lesson for Finance year 1");
	lesson1Year1Finance1.setGroups(new ArrayList<>());
	lesson1Year1Finance1.getGroups().addAll(year1Finance.getGroups());
	System.out.println("-- Create students");
	Student student1FinanceYear1 = new Student("1", "Name1", "LastName1", faculty, specialityFinance, group1FinanceYear1);
	Student student1BankingYear1 = new Student("1", "Name1", "LastName1", faculty, specialityBanking, group1BankingYear1);
	System.out.println("-- Add student to group");
	group1FinanceYear1.setStudents(new ArrayList<>());
	group1FinanceYear1.getStudents().add(student1FinanceYear1);		
	System.out.println("-- Using timetable");
	System.out.println(timetableFinanceYear1.showTimetableByStudent(student1FinanceYear1, LocalDate.of(2020, 12, 1), LocalDate.of(2020, 12, 3)));
	System.out.println(timetableFinanceYear1.showTimetableByStudent(student1BankingYear1, LocalDate.of(2020, 12, 1), LocalDate.of(2020, 12, 2)));
	System.out.println(timetableFinanceYear1.showTimetableByTeacher(teacher1, LocalDate.of(2020, 12, 1), LocalDate.of(2020, 12, 2)));
	System.out.println("-- Using holidays");
	System.out.println(universityOffice.showHolidays());
	System.out.println("-- Create vocation");
	Vocation vocation = new Vocation("yearly", LocalDate.of(2020, 1, 1), teacher1, LocalDate.of(2021, 1, 1), LocalDate.of(2021, 1, 15));
	System.out.println("-- Add vocation to deanceOffice");
	deansOffice.setVocations(new ArrayList<>());
	deansOffice.getVocations().add(vocation);
	System.out.println("-- Using vocations");
	System.out.println(deansOffice.showVocationByTeacher(teacher1, LocalDate.of(2021, 1, 1), LocalDate.of(2021, 12, 31)));
    }
}
